### ISSUE TITLE
Windows 10 support

### ISSUE THREAD

**Issue by ghost** [SDLash3D/xash3d#102]
But my game has no sound, and can not windowing.

**Comment by a1batross** [comment]
What? On my Win10 PC git builds runs perfectly.

**Comment by mainwindow** [comment]
@a1batross What is your Half-Life Client Version? I use the lastest steam version.

**Comment by a1batross** [comment]
I use it too. 
I don't know how to reproduce your bug. I don't think that's engine related bug.

**Comment by mainwindow** [comment]
@a1batross But I have a question, what client.dll and hl.dll version I should using?

**Comment by a1batross** [comment]
Any. There is no restrictions.
