### ISSUE TITLE
Ubuntu build fails

### ISSUE THREAD

**Issue by lazanet** [SDLash3D/xash3d#103]
I built Xash some time ago on 14.04 after going trough dependency hell using:
https://gist.github.com/lazanet/92f14c3ffe969ea5be7c
It always core dumped before anything was on screen 

However 32 bit build libraries are missing at all from ubuntu 15.10 repos, so I tried to hack it nasty way:
https://gist.github.com/lazanet/6e78ff656bfddc64d7a2
Ubuntu now auto removes packages that I manually installed after using apt-get -f install to fix broken dependencies. Build fails at libxashmenu.so
http://pastebin.com/BTEraHig

Any help would be appreciated :)

**Comment by a1batross** [comment]
I got this building on my OBS home repo, maybe scripts for it may help you. 

https://build.opensuse.org/package/show/home:a1batross/xash3d-sdl

**Comment by a1batross** [comment]
I also recommend you write cmake command more detailed. -DXASH_SDL=yes -DXASH_X11=yes

In build log you are trying to link i386 binary with amd64 libs. Install i386 versions of these binaries, rerun CMake and anything will be ok.

**Comment by a1batross** [comment]
Also, instead "make" command you can write "make VERBOSE=1". It will help you debug.

**Comment by openglhk** [comment]
apt-get install g++-multilib ?

**Comment by openglhk** [comment]
on Ubuntu 32bit

git submodule init && git submodule update
mkdir -p build
cd build/
apt-get install cmake
apt-get install libSDL2-dev
apt-get install build-essential
cmake -DHL_SDK_DIR=../hlsdk -DXASH_SDL=yes -DXASH_VGUI=yes -DCMAKE_OSX_ARCHITECTURES=i386 ../
make

this issue should close..
