### ISSUE TITLE
Build failed: Cannot open include file: 'VGUI.h': No such file or directory

### ISSUE THREAD

**Issue by Louis-MarieMatthews** [SDLash3D/xash3d#123]
Hello there!

I downloaded xash3d-master.zip, extracted it in Downloads, downloaded SDL2-devel-2.0.3-VC.zip, extracted it in Downloads and renamed it to "SDL2". When I try to compile xash.sln with Ms Visual Studio Community 2013, I got this error: Cannot open include file: 'VGUI.h': No such file or directory

Anyone know what's the cause?

Cheers!

**Comment by nekonomicon** [comment]
Needs manual download hlsdk from repo halflife and copy to xash3d/hlsdk.

**Comment by Louis-MarieMatthews** [comment]
Build suceeded, thanks man! :)
