### ISSUE TITLE
Cannot load any map.

### ISSUE THREAD

**Issue by CrusoeDaWolf** [SDLash3D/xash3d#134]
So, I recently built Xash3D from scratch again. Everything compiled successfully. I made a separate folder for Xash and moved all the files and folders. I moved vgui_support.dll inside the valve folder and copied the x86 SDL2.dll into the Xash folder. I also had the 3153 build and copied over the vgui.dll from there as well as the extras (For the menu and DLLs). Once I was done, I launched Xash and everything seemed normal until I tried to load up both the hazard course and singleplayer. It would seem to load everything normally until the little loading bar was half-way to the end when suddenly Xash crashed. I'm not sure how to log the files so if any one can tell me how to do so, it would really help. :c 

My directory looks like this:
valve (Folder)
xash.exe
menu.dll
SDL2.dll
vgui.dll
vgui_support.dll (Both in and outside the valve folder)
xash.dll
xash_sdl.dll
Xash3D (Shortcut with -console and -dev 5 paramters)

**Comment by nekonomicon** [comment]
Bad compatibility with different versions of vgui.
You can take vgui.dll(400kb size) from old builds.
https://github.com/SDLash3D/xash3d/releases

**Comment by nekonomicon** [comment]
Use parameters:
`-dev 5 -log`
Attach a file engine.log.

**Comment by CrusoeDaWolf** [comment]
Alright. I will do that later. I forgot to mention that I have a backup of all my config files and I reused them. I do recall messing around in config.cfg earlier, however I did not explain the full story.


So, earlier before the problem I had setup Base Defense in Xash and everything worked correctly except on the right, some of the UI wouldn't show (No ammo, messages, etc.). The same problem occured with Firearms, so I thought I needed to use the vgui.dll from the normal HL directroy so I replaced the DLL that came with Xash 3153. Xash launched up, but I couldn't load anything (It didn't crash however. In the console, it would load up everything but just say "Game Started") so I went back to the vgui.dll that came with build 3153. I tried loading a map (In any mod) and the Xash would just crash at the half way point of loading a map.

Note, during this time I had also messed around in the config.cfg file, so perhaps I need to just delete it and reset everything back up again?

**Comment by Sworfly** [comment]
I have a similar problem, but a plus to it after exiting the application or kill them (in the case of an unresponsive graphics) missing window titles.
Fedora 23 , KDE5, 4.4.6-301.fc23.x86_64
log attached.

[У меня аналогичная проблема, но плюсом к ней после выхода из приложения или его убийства(в случае зависания графики) пропадают заголовки окон.
Fedora 23, KDE5, 4.4.6-301.fc23.x86_64
лог прилагаю.]
[engine.log.zip](https://github.com/SDLash3D/xash3d/files/222675/engine.log.zip)

**Comment by nekonomicon** [comment]
@Sworfly, It seems trouble with vgui.
You can try build vguiless client from hlsdk-client repo.

**Comment by mittorn** [comment]
Do you use .dll or .so libraries?
To use dll loader, you should specify -vguiloader with path to vgui_support dll.
https://github.com/SDLash3D/vgui_support_bin
Use this version, only it works In linux.
Also, you should use vgui.dll that comes with half-life. File size should be about 400 kB, not 352.
Use -dll to specify server library path,-clientlib to specify client library path.
It will be autonaticly detected, if it .so or .dll

**Comment by CrusoeDaWolf** [comment]
Turns out it was a configuration problem. I reset up everything without using my backup CFGs and it finally worked. c:
