### ISSUE TITLE
SV_NewMap: map pve_building doesn't have a valid spawnpoint (Close this please! Thanks c:)

### ISSUE THREAD

**Issue by CrusoeDaWolf** [SDLash3D/xash3d#135]
Hello. I've recently tried starting a Base Defense listen server and attempted to load one of the maps (pve_building), however it gives me, "SV_NewMap: map pve_building doesn't have a valid spawnpoint"

I've decompiled the map and it has four different info_player_start. Everything seems normal. I can play this map in singleplayer and I tried this on my friends computer (Steam version, not Xash3D) and it can load the map up perfectly fine. Is there any entity I need to change to get pve_building to work in multiplayer?
 
OS: Windows 8.1
Arch: 64-bit.

EDIT:
Never mind. The creator of the mod messaged me with a fix. Go within gameinfo.txt and change the following line:

mp_entity		"info_player_deathmatch"

To:

mp_entity		"info_player_start"

**Comment by a1batross** [comment]
Yes. Multiplayer spawn entity is info_player_deathmatch.
