### ISSUE TITLE
Cannot Build On Arch Linux

### ISSUE THREAD

**Issue by CrusoeDaWolf** [SDLash3D/xash3d#138]
So, I am currently trying to setup Xash3D on my dad's computer (Arch Linux, ApricityOS). When I begin with using cmake, I get this:

cmake -DHL_SDK_DIR=../hlsdk -DXASH_SDL=yes -DXASH_VGUI=yes ../
-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
<FindSDL2.cmake>
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Could NOT find Threads (missing:  Threads_FOUND) 
</FindSDL2.cmake>
-- Found SDL2: /usr/lib64/libSDL2main.a;/usr/lib64/libSDL2.so  
<FindSDL2.cmake>
-- Could NOT find Threads (missing:  Threads_FOUND) 
</FindSDL2.cmake>
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pavels/Downloads/xash3d/build

When I use the make command, I get this:

Scanning dependencies of target xashmenu
[  1%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_newgame.cpp.o
[  1%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_controls.cpp.o
[  2%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_advcontrols.cpp.o
[  3%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_playersetup.cpp.o
In file included from /home/pavels/Downloads/xash3d/mainui/../common/cl_entity.h:63:0,
                 from /home/pavels/Downloads/xash3d/mainui/menu_playersetup.cpp:28:
/home/pavels/Downloads/xash3d/mainui/../common/entity_state.h:121:21: fatal error: pm_info.h: No such file or directory
compilation terminated.
mainui/CMakeFiles/xashmenu.dir/build.make:134: recipe for target 'mainui/CMakeFiles/xashmenu.dir/menu_playersetup.cpp.o' failed
make[2]: *** [mainui/CMakeFiles/xashmenu.dir/menu_playersetup.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'mainui/CMakeFiles/xashmenu.dir/all' failed
make[1]: *** [mainui/CMakeFiles/xashmenu.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

I have installed both SDL and SDL2 and I setup everything correctly (Made a folder called xash3d, downloaded the hlsdk). Any help? :c

**Comment by CrusoeDaWolf** [comment]
make VERBOSE=1 output:

/usr/bin/cmake -H/home/pavels/Downloads/xash3d -B/home/pavels/Downloads/xash3d/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/pavels/Downloads/xash3d/build/CMakeFiles /home/pavels/Downloads/xash3d/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/pavels/Downloads/xash3d/build'
make -f mainui/CMakeFiles/xashmenu.dir/build.make mainui/CMakeFiles/xashmenu.dir/depend
make[2]: Entering directory '/home/pavels/Downloads/xash3d/build'
cd /home/pavels/Downloads/xash3d/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/pavels/Downloads/xash3d /home/pavels/Downloads/xash3d/mainui /home/pavels/Downloads/xash3d/build /home/pavels/Downloads/xash3d/build/mainui /home/pavels/Downloads/xash3d/build/mainui/CMakeFiles/xashmenu.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/pavels/Downloads/xash3d/build'
make -f mainui/CMakeFiles/xashmenu.dir/build.make mainui/CMakeFiles/xashmenu.dir/build
make[2]: Entering directory '/home/pavels/Downloads/xash3d/build'
[  1%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_playersetup.cpp.o
cd /home/pavels/Downloads/xash3d/build/mainui && /usr/bin/c++   -Dxashmenu_EXPORTS -I/home/pavels/Downloads/xash3d/mainui/../common -I/home/pavels/Downloads/xash3d/mainui/../engine -I/home/pavels/Downloads/xash3d/hlsdk/pm_shared  -m32 -w -fPIC   -o CMakeFiles/xashmenu.dir/menu_playersetup.cpp.o -c /home/pavels/Downloads/xash3d/mainui/menu_playersetup.cpp
In file included from /home/pavels/Downloads/xash3d/mainui/../common/cl_entity.h:63:0,
                 from /home/pavels/Downloads/xash3d/mainui/menu_playersetup.cpp:28:
/home/pavels/Downloads/xash3d/mainui/../common/entity_state.h:121:21: fatal error: pm_info.h: No such file or directory
compilation terminated.
mainui/CMakeFiles/xashmenu.dir/build.make:134: recipe for target 'mainui/CMakeFiles/xashmenu.dir/menu_playersetup.cpp.o' failed
make[2]: *** [mainui/CMakeFiles/xashmenu.dir/menu_playersetup.cpp.o] Error 1
make[2]: Leaving directory '/home/pavels/Downloads/xash3d/build'
CMakeFiles/Makefile2:85: recipe for target 'mainui/CMakeFiles/xashmenu.dir/all' failed
make[1]: *** [mainui/CMakeFiles/xashmenu.dir/all] Error 2
make[1]: Leaving directory '/home/pavels/Downloads/xash3d/build'
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by a1batross** [comment]
git submodule init && git submodule update


2016-04-24 23:28 GMT+03:00 CrusoeDaWolf <notifications@github.com>:

**Comment by CrusoeDaWolf** [comment]
Didn't solve anything. Same problem. :c

**Comment by CrusoeDaWolf** [comment]
Scanning dependencies of target xashmenu
[  1%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_newgame.cpp.o
[  1%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_controls.cpp.o
a[  2%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_advcontrols.cpp.o
s[  3%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_playersetup.cpp.o
[  3%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_video.cpp.o
[  4%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_loadgame.cpp.o
[  4%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_configuration.cpp.o
[  5%] Building CXX object mainui/CMakeFiles/xashmenu.dir/utils.cpp.o
[  6%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_gameoptions.cpp.o
[  6%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_touchbuttons.cpp.o
[  7%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_savegame.cpp.o
[  8%] Building CXX object mainui/CMakeFiles/xashmenu.dir/udll_int.cpp.o
[  8%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_multiplayer.cpp.o
[  9%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_main.cpp.o
[ 10%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_touchoptions.cpp.o
[ 10%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_internetgames.cpp.o
[ 11%] Building CXX object mainui/CMakeFiles/xashmenu.dir/ui_title_anim.cpp.o
[ 12%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_touch.cpp.o
[ 12%] Building CXX object mainui/CMakeFiles/xashmenu.dir/basemenu.cpp.o
[ 13%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_saveload.cpp.o
[ 13%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_touchedit.cpp.o
[ 14%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_customgame.cpp.o
[ 15%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_strings.cpp.o
[ 15%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_creategame.cpp.o
[ 16%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_audio.cpp.o
[ 17%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_btns.cpp.o
[ 17%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_filedialog.cpp.o
[ 18%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_vidmodes.cpp.o
[ 19%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_credits.cpp.o
[ 19%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_vidoptions.cpp.o
[ 20%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_langame.cpp.o
[ 21%] Linking CXX shared library libxashmenu.so
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/libstdc++.a when searching for -lstdc++
/usr/bin/ld: skipping incompatible /lib/../lib/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /lib/../lib/libstdc++.a when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libstdc++.a when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../libstdc++.a when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/libstdc++.a when searching for -lstdc++
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/libm.a when searching for -lm
/usr/bin/ld: skipping incompatible /lib/../lib/libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /lib/../lib/libm.a when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libm.a when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../libm.a when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/libm.a when searching for -lm
/usr/bin/ld: cannot find -lm
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: skipping incompatible /lib/../lib/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: skipping incompatible /usr/lib/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/libc.so when searching for -lc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/libc.a when searching for -lc
/usr/bin/ld: skipping incompatible /lib/../lib/libc.so when searching for -lc
/usr/bin/ld: skipping incompatible /lib/../lib/libc.a when searching for -lc
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libc.so when searching for -lc
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libc.a when searching for -lc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../libc.so when searching for -lc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../libc.a when searching for -lc
/usr/bin/ld: skipping incompatible /usr/lib/libc.so when searching for -lc
/usr/bin/ld: skipping incompatible /usr/lib/libc.a when searching for -lc
/usr/bin/ld: cannot find -lc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: skipping incompatible /lib/../lib/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: skipping incompatible /usr/lib/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
collect2: error: ld returned 1 exit status
mainui/CMakeFiles/xashmenu.dir/build.make:874: recipe for target 'mainui/libxashmenu.so' failed
make[2]: *** [mainui/libxashmenu.so] Error 1
CMakeFiles/Makefile2:85: recipe for target 'mainui/CMakeFiles/xashmenu.dir/all' failed
make[1]: *** [mainui/CMakeFiles/xashmenu.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nekonomicon** [comment]
>Found SDL2: /usr/lib64/libSDL2main.a;/usr/lib64/libSDL2.so

32bit libs is neaded.

**Comment by CrusoeDaWolf** [comment]
Hold up. Change of plans. I installed gcc-multilib instead and got 99% until this happened:

Scanning dependencies of target xashmenu
[  1%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_newgame.cpp.o
[  1%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_controls.cpp.o
[  2%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_advcontrols.cpp.o
[  3%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_playersetup.cpp.o
[  3%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_video.cpp.o
[  4%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_loadgame.cpp.o
[  4%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_configuration.cpp.o
[  5%] Building CXX object mainui/CMakeFiles/xashmenu.dir/utils.cpp.o
[  6%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_gameoptions.cpp.o
[  6%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_touchbuttons.cpp.o
[  7%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_savegame.cpp.o
[  8%] Building CXX object mainui/CMakeFiles/xashmenu.dir/udll_int.cpp.o
[  8%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_multiplayer.cpp.o
[  9%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_main.cpp.o
[ 10%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_touchoptions.cpp.o
[ 10%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_internetgames.cpp.o
[ 11%] Building CXX object mainui/CMakeFiles/xashmenu.dir/ui_title_anim.cpp.o
[ 12%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_touch.cpp.o
[ 12%] Building CXX object mainui/CMakeFiles/xashmenu.dir/basemenu.cpp.o
[ 13%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_saveload.cpp.o
[ 13%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_touchedit.cpp.o
[ 14%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_customgame.cpp.o
[ 15%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_strings.cpp.o
[ 15%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_creategame.cpp.o
[ 16%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_audio.cpp.o
[ 17%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_btns.cpp.o
[ 17%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_filedialog.cpp.o
[ 18%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_vidmodes.cpp.o
[ 19%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_credits.cpp.o
[ 19%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_vidoptions.cpp.o
[ 20%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_langame.cpp.o
[ 21%] Linking CXX shared library libxashmenu.so
[ 21%] Built target xashmenu
Scanning dependencies of target vgui_support
[ 21%] Building CXX object vgui_support/CMakeFiles/vgui_support.dir/vgui_int.cpp.o
[ 22%] Building CXX object vgui_support/CMakeFiles/vgui_support.dir/vgui_surf.cpp.o
[ 22%] Building CXX object vgui_support/CMakeFiles/vgui_support.dir/vgui_input.cpp.o
[ 23%] Building CXX object vgui_support/CMakeFiles/vgui_support.dir/vgui_font.cpp.o
[ 24%] Building CXX object vgui_support/CMakeFiles/vgui_support.dir/vgui_clip.cpp.o
[ 24%] Linking CXX shared library libvgui_support.so
[ 24%] Built target vgui_support
Scanning dependencies of target xash
[ 25%] Building C object engine/CMakeFiles/xash.dir/server/sv_save.c.o
[ 26%] Building C object engine/CMakeFiles/xash.dir/server/sv_frame.c.o
[ 26%] Building C object engine/CMakeFiles/xash.dir/server/sv_log.c.o
[ 27%] Building C object engine/CMakeFiles/xash.dir/server/sv_pmove.c.o
[ 28%] Building C object engine/CMakeFiles/xash.dir/server/sv_move.c.o
[ 28%] Building C object engine/CMakeFiles/xash.dir/server/sv_phys.c.o
[ 29%] Building C object engine/CMakeFiles/xash.dir/server/sv_world.c.o
[ 29%] Building C object engine/CMakeFiles/xash.dir/server/sv_cmds.c.o
[ 30%] Building C object engine/CMakeFiles/xash.dir/server/sv_game.c.o
[ 31%] Building C object engine/CMakeFiles/xash.dir/server/sv_custom.c.o
[ 31%] Building C object engine/CMakeFiles/xash.dir/server/sv_client.c.o
[ 32%] Building C object engine/CMakeFiles/xash.dir/server/sv_main.c.o
[ 33%] Building C object engine/CMakeFiles/xash.dir/server/sv_init.c.o
[ 33%] Building C object engine/CMakeFiles/xash.dir/client/gl_mirror.c.o
[ 34%] Building C object engine/CMakeFiles/xash.dir/client/s_mix.c.o
[ 35%] Building C object engine/CMakeFiles/xash.dir/client/s_load.c.o
[ 35%] Building C object engine/CMakeFiles/xash.dir/client/cl_video.c.o
[ 36%] Building C object engine/CMakeFiles/xash.dir/client/cl_game.c.o
[ 37%] Building C object engine/CMakeFiles/xash.dir/client/gl_vidnt.c.o
[ 37%] Building C object engine/CMakeFiles/xash.dir/client/cl_menu.c.o
[ 38%] Building C object engine/CMakeFiles/xash.dir/client/s_mouth.c.o
[ 38%] Building C object engine/CMakeFiles/xash.dir/client/cl_parse.c.o
[ 39%] Building C object engine/CMakeFiles/xash.dir/client/gl_decals.c.o
[ 40%] Building C object engine/CMakeFiles/xash.dir/client/cl_frame.c.o
[ 40%] Building C object engine/CMakeFiles/xash.dir/client/cl_scrn.c.o
[ 41%] Building C object engine/CMakeFiles/xash.dir/client/cl_mobile.c.o
[ 42%] Building C object engine/CMakeFiles/xash.dir/client/gl_rmain.c.o
[ 42%] Building C object engine/CMakeFiles/xash.dir/client/s_main.c.o
[ 43%] Building C object engine/CMakeFiles/xash.dir/client/cl_view.c.o
[ 44%] Building C object engine/CMakeFiles/xash.dir/client/s_vox.c.o
[ 44%] Building C object engine/CMakeFiles/xash.dir/client/gl_rmath.c.o
[ 45%] Building C object engine/CMakeFiles/xash.dir/client/gl_cull.c.o
[ 46%] Building C object engine/CMakeFiles/xash.dir/client/gl_image.c.o
[ 46%] Building C object engine/CMakeFiles/xash.dir/client/s_backend.c.o
[ 47%] Building C object engine/CMakeFiles/xash.dir/client/s_dsp.c.o
[ 47%] Building C object engine/CMakeFiles/xash.dir/client/gl_studio.c.o
[ 48%] Building C object engine/CMakeFiles/xash.dir/client/gl_refrag.c.o
[ 49%] Building C object engine/CMakeFiles/xash.dir/client/s_stream.c.o
[ 49%] Building C object engine/CMakeFiles/xash.dir/client/gl_warp.c.o
[ 50%] Building C object engine/CMakeFiles/xash.dir/client/gl_backend.c.o
[ 51%] Building C object engine/CMakeFiles/xash.dir/client/cl_tent.c.o
[ 51%] Building C object engine/CMakeFiles/xash.dir/client/cl_remap.c.o
[ 52%] Building C object engine/CMakeFiles/xash.dir/client/gl_vidnt_common.c.o
[ 53%] Building C object engine/CMakeFiles/xash.dir/client/gl_rsurf.c.o
[ 53%] Building C object engine/CMakeFiles/xash.dir/client/cl_events.c.o
[ 54%] Building C object engine/CMakeFiles/xash.dir/client/s_utils.c.o
[ 54%] Building C object engine/CMakeFiles/xash.dir/client/cl_cmds.c.o
[ 55%] Building C object engine/CMakeFiles/xash.dir/client/cl_demo.c.o
[ 56%] Building C object engine/CMakeFiles/xash.dir/client/gl_rlight.c.o
[ 56%] Building C object engine/CMakeFiles/xash.dir/client/vgui/vgui_draw.c.o
[ 57%] Building C object engine/CMakeFiles/xash.dir/client/cl_main.c.o
[ 58%] Building C object engine/CMakeFiles/xash.dir/client/gl_draw.c.o
[ 58%] Building C object engine/CMakeFiles/xash.dir/client/gl_vidnt_android.c.o
[ 59%] Building C object engine/CMakeFiles/xash.dir/client/gl_sprite.c.o
[ 60%] Building C object engine/CMakeFiles/xash.dir/client/gl_rmisc.c.o
[ 60%] Building C object engine/CMakeFiles/xash.dir/client/cl_pmove.c.o
[ 61%] Building C object engine/CMakeFiles/xash.dir/client/gl_rpart.c.o
[ 62%] Building C object engine/CMakeFiles/xash.dir/client/gl_beams.c.o
[ 62%] Building C object engine/CMakeFiles/xash.dir/common/network.c.o
[ 63%] Building C object engine/CMakeFiles/xash.dir/common/avikit.c.o
[ 63%] Building C object engine/CMakeFiles/xash.dir/common/common.c.o
[ 64%] Building C object engine/CMakeFiles/xash.dir/common/touch.c.o
[ 65%] Building C object engine/CMakeFiles/xash.dir/common/keys.c.o
[ 65%] Building C object engine/CMakeFiles/xash.dir/common/world.c.o
[ 66%] Building C object engine/CMakeFiles/xash.dir/common/sdl/events.c.o
[ 67%] Building C object engine/CMakeFiles/xash.dir/common/net_encode.c.o
[ 67%] Building C object engine/CMakeFiles/xash.dir/common/console.c.o
[ 68%] Building C object engine/CMakeFiles/xash.dir/common/net_buffer.c.o
[ 69%] Building C object engine/CMakeFiles/xash.dir/common/input.c.o
[ 69%] Building C object engine/CMakeFiles/xash.dir/common/pm_surface.c.o
[ 70%] Building C object engine/CMakeFiles/xash.dir/common/crtlib.c.o
[ 71%] Building C object engine/CMakeFiles/xash.dir/common/imagelib/img_utils.c.o
[ 71%] Building C object engine/CMakeFiles/xash.dir/common/imagelib/img_tga.c.o
[ 72%] Building C object engine/CMakeFiles/xash.dir/common/imagelib/img_bmp.c.o
[ 72%] Building C object engine/CMakeFiles/xash.dir/common/imagelib/img_wad.c.o
[ 73%] Building C object engine/CMakeFiles/xash.dir/common/imagelib/img_dds.c.o
[ 74%] Building C object engine/CMakeFiles/xash.dir/common/imagelib/img_quant.c.o
[ 74%] Building C object engine/CMakeFiles/xash.dir/common/imagelib/img_main.c.o
[ 75%] Building C object engine/CMakeFiles/xash.dir/common/cmd.c.o
[ 76%] Building C object engine/CMakeFiles/xash.dir/common/model.c.o
[ 76%] Building C object engine/CMakeFiles/xash.dir/common/crclib.c.o
[ 77%] Building C object engine/CMakeFiles/xash.dir/common/mod_studio.c.o
[ 78%] Building C object engine/CMakeFiles/xash.dir/common/input_evdevkey.c.o
[ 78%] Building C object engine/CMakeFiles/xash.dir/common/net_chan.c.o
[ 79%] Building C object engine/CMakeFiles/xash.dir/common/library.c.o
[ 79%] Building C object engine/CMakeFiles/xash.dir/common/mathlib.c.o
[ 80%] Building C object engine/CMakeFiles/xash.dir/common/gamma.c.o
[ 81%] Building C object engine/CMakeFiles/xash.dir/common/launcher.c.o
[ 81%] Building C object engine/CMakeFiles/xash.dir/common/build.c.o
[ 82%] Building C object engine/CMakeFiles/xash.dir/common/con_utils.c.o
[ 83%] Building C object engine/CMakeFiles/xash.dir/common/soundlib/snd_main.c.o
[ 83%] Building C object engine/CMakeFiles/xash.dir/common/soundlib/snd_utils.c.o
[ 84%] Building C object engine/CMakeFiles/xash.dir/common/soundlib/snd_mp3.c.o
[ 85%] Building C object engine/CMakeFiles/xash.dir/common/soundlib/snd_wav.c.o
[ 85%] Building C object engine/CMakeFiles/xash.dir/common/soundlib/libmpg/decode_i386.c.o
[ 86%] Building C object engine/CMakeFiles/xash.dir/common/soundlib/libmpg/common.c.o
[ 87%] Building C object engine/CMakeFiles/xash.dir/common/soundlib/libmpg/layer2.c.o
[ 87%] Building C object engine/CMakeFiles/xash.dir/common/soundlib/libmpg/layer3.c.o
[ 88%] Building C object engine/CMakeFiles/xash.dir/common/soundlib/libmpg/tabinit.c.o
[ 88%] Building C object engine/CMakeFiles/xash.dir/common/soundlib/libmpg/dct64_i386.c.o
[ 89%] Building C object engine/CMakeFiles/xash.dir/common/soundlib/libmpg/interface.c.o
[ 90%] Building C object engine/CMakeFiles/xash.dir/common/filesystem.c.o
[ 90%] Building C object engine/CMakeFiles/xash.dir/common/sys_win.c.o
[ 91%] Building C object engine/CMakeFiles/xash.dir/common/cvar.c.o
[ 92%] Building C object engine/CMakeFiles/xash.dir/common/hpak.c.o
[ 92%] Building C object engine/CMakeFiles/xash.dir/common/random.c.o
[ 93%] Building C object engine/CMakeFiles/xash.dir/common/infostring.c.o
[ 94%] Building C object engine/CMakeFiles/xash.dir/common/net_huff.c.o
[ 94%] Building C object engine/CMakeFiles/xash.dir/common/host.c.o
[ 95%] Building C object engine/CMakeFiles/xash.dir/common/sys_con.c.o
[ 96%] Building C object engine/CMakeFiles/xash.dir/common/titles.c.o
[ 96%] Building C object engine/CMakeFiles/xash.dir/common/zone.c.o
[ 97%] Building C object engine/CMakeFiles/xash.dir/common/pm_trace.c.o
[ 97%] Building C object engine/CMakeFiles/xash.dir/common/matrixlib.c.o
[ 98%] Building C object engine/CMakeFiles/xash.dir/platform/android/android.c.o
[ 99%] Linking C shared library libxash.so
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../libSDL2main.a when searching for -lSDL2main
/usr/bin/ld: skipping incompatible /usr/lib/libSDL2main.a when searching for -lSDL2main
/usr/bin/ld: cannot find -lSDL2main
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../libSDL2.so when searching for -lSDL2
/usr/bin/ld: skipping incompatible /usr/lib/libSDL2.so when searching for -lSDL2
/usr/bin/ld: cannot find -lSDL2
collect2: error: ld returned 1 exit status
engine/CMakeFiles/xash.dir/build.make:3060: recipe for target 'engine/libxash.so' failed
make[2]: *** [engine/libxash.so] Error 1
CMakeFiles/Makefile2:195: recipe for target 'engine/CMakeFiles/xash.dir/all' failed
make[1]: *** [engine/CMakeFiles/xash.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by CrusoeDaWolf** [comment]
Also, will install 32-bit libs and see if it works.

**Comment by CrusoeDaWolf** [comment]
Build succesful! Thank you guys! By the way, did it also build the DLL loader?

**Comment by a1batross** [comment]
Pass -DXASH_DLL_LOADER=yes to CMake and it will build it too.

**Comment by CrusoeDaWolf** [comment]
Strange. I'm getting 'Unable to load the libxash.so' when I launch Xash, but the library is there.

**Comment by a1batross** [comment]
Look in the console, it will show the errors of loading the library.

Also, maybe you forgot to copy libloader.so(if you compiled DLL loader),
libxash.so, xash3d and xash3d.sh in one place? Or set LD_LIBRARY_PATH?

**Comment by CrusoeDaWolf** [comment]
Hold up. I'm going to clean it up on my dad's computer then compile it on my own Arch machine. Will reply with results in a few minutes.

**Comment by CrusoeDaWolf** [comment]
Sorry for the SUPER late reply. Everything is all good here. By the way, say if I want to launch a mod or something but I'm too lazy to move the folder, is there a parameter that allows me to specify the directory of the mod?

**Comment by a1batross** [comment]
-game.
For example, `-game cstrike`. 

Also you can recompile game_launch for every mod, but it's insane and more for standalone builds.
