### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by xDShot** [SDLash3D/xash3d#14]
OS -Manjaro Linux x64.

Log: http://pastebin.com/LSJnWeb2

**Comment by a1batross** [comment]
Проверь, существует ли /home/xdshot/halflife/linux/vgui.so.

**Comment by xDShot** [comment]
Да, он там есть.
Пробовал распаковывать Half-Life SDK в /opt/halflife/. Тоже самое.

**Comment by a1batross** [comment]
Странно. Ладно, приеду уже завтра домой, гляну что не так со сборкой.

**Comment by xDShot** [comment]
Почти такая же ошибка в Linux Mint x64. Действия те же:

Linking CXX shared library libxash.so
/usr/bin/ld: skipping incompatible /home/xdshot/halflife/linux/vgui.so when searching for /home/xdshot/halflife/linux/vgui.so
/usr/bin/ld: cannot find /home/xdshot/halflife/linux/vgui.so
/usr/bin/ld: skipping incompatible /home/xdshot/halflife/linux/vgui.so when searching for /home/xdshot/halflife/linux/vgui.so
/usr/bin/ld: cannot find /home/xdshot/halflife/linux/vgui.so
collect2: error: ld returned 1 exit status
make[2]: *** [engine/libxash.so] Ошибка 1
make[1]: *** [engine/CMakeFiles/xash.dir/all] Ошибка 2
make: *** [all] Ошибка 2

**Comment by xDShot** [comment]
Таки собралось успешно на Linux Mint *x32*

**Comment by a1batross** [comment]
Всё, до меня дошло. VGUI -- проприетарная библиотека и существует только
под 32-битные системы.
Под 64 бита есть только два способа использовать этот порт:
1) Собрать ксаш без VGUI (реализовано в ветке android_port)
2) Собрать его под 32 бита. С кучей 32 битных библиотек. Понятия не имею
как это сделать.

**Comment by sballu** [comment]
Could it work if you add
set_target_properties(${XASH_ENGINE_LIBRARY} PROPERTIES COMPILE_FLAGS "-m32" LINK_FLAGS "-m32")
in engine/CMakeLists.txt ?

**Comment by xDShot** [comment]
No, I'm still getting this error.

**Comment by a1batross** [comment]
Наверное, ошибка всё ещё присутствует, так как у тебя теперь нет 32-битного SDL2 и прочих зависимостей.

**Comment by xDShot** [comment]
Внезапно, android_port ветвь собралась на x64.

**Comment by xDShot** [comment]
@a1batross 
Все необходимые sdl2-инклюды и библиотеки в системе присутсвуют.

**Comment by a1batross** [comment]
Так она собралась, потому что VGUI теперь необязательная зависимость.
