### ISSUE TITLE
Host_Error: CL_ParseUserMessage: illegable server message 97

### ISSUE THREAD

**Issue by CrusoeDaWolf** [SDLash3D/xash3d#141]
Hi, so I'm having a problem with my Base Defense server. Whenever I join my server and my friend attempts to connect, he gets this message. Whenever he connects first and I try to connect, I get the error message. What does it mean exactly and how should I go about fixing it? Is it a problem with the client or server config?

**Comment by a1batross** [comment]
It's message to client. Client should handle it.

**Comment by CrusoeDaWolf** [comment]
Never mind. I had to type this into the console:
timeout 60

After that, both of us could join.
