### ISSUE TITLE
Cannot Download Custom Map from my Server

### ISSUE THREAD

**Issue by CrusoeDaWolf** [SDLash3D/xash3d#144]
So, I have recently setup a server and loaded up a custom map (boot_campx). I set sv_allow_upload to one, but whenever I try to connect from my other computer, it tells me that the map couldn't be found. Did I do something wrong or is there something else that I have to do?

**Comment by nekonomicon** [comment]
>sv_allow_upload

sv_allow_download

**Comment by CrusoeDaWolf** [comment]
I already set that to one. I'm trying to connect through build 3366 from moddb. The latest release from github works fine though.

**Comment by nekonomicon** [comment]
>build 3366 from moddb.

It's original xash3d by Uncle Mike.
https://github.com/a1batross/Xash3D_original

It's not support some features from xash3d sdl.

**Comment by CrusoeDaWolf** [comment]
Ah. Alright. I'll be compiling or using the release from git then. Thanks!
