### ISSUE TITLE
XashDS Server stuck in "Adding your server to master server list"

### ISSUE THREAD

**Issue by DeicPro** [SDLash3D/xash3d#145]
> Refer: [How to set up a Xash3D Dedicated Server on Debian or Ubuntu](https://github.com/SDLash3D/xash3d/wiki/How-to-set-up-a-Xash3D-Dedicated-Server-on-Debian-or-Ubuntu)

**My OS**
Ubuntu 16.04 64-bit

I got this:
```
$ xashds -game cstrike
XashDS is installed in system.
Choosed $XASH3D_BASEDIR as /home/xashds/xashds/
================================================================================
	 (build 3224) started at May22 2016 [10:04.42]
================================================================================
[10:04:42] Dll loaded for mod Counter-Strike
[10:04:42] execing config.cfg
[10:04:42] execing server.cfg
[10:04:42] Server IP address: 127.0.1.1:27016
[10:04:42] Spawn Server: de_dust2
[10:04:42] server: GAME SKILL LEVEL:1
[10:04:42] SV_LoadFromFile: 0 entities inhibited
[10:04:42] 32 player server started
[10:04:42] Adding your server to master server list

```
I'm stuck there.

-

**Off-topic**
I had to change some lines in `/usr/games/xashds` because with default code I couldn't launch `/usr/games/lib/xashds/xash3d` correctly. [Gist](https://gist.github.com/DeicPro/9f16721d1625ecfa1003c333bec8dacf/revisions?diff=unified)

**Comment by a1batross** [comment]
It isn't stuck. Try to connect to your server. Log shows that server with 32 players was started and master server was notified about your server.

> I had to change some lines in /usr/games/xashds because with default code I couldn't launch /usr/games/lib/xashds/xash3d correctly. Gist

Yeah, there is a bug. LD_LIBRARY_PATH must be exported. Thanks I will fix it.

Also, you can just set XASH3D_BASEDIR before executing script: `XASH3D_BASEDIR="$HOME/xashds" xashds -game cstrike`

**Comment by DeicPro** [comment]
I was waiting for `[10:04:42] Server is running correctly` or something... My bad x)

But I don't see my server in the server list and I can't join from console too. I got:
```
>\connect 82.158.147.151:27016
server 82.158.147.151:27016
```
and nothing more.

**Comment by a1batross** [comment]
Do you have opened ports?

**Comment by DeicPro** [comment]
Port closed, my bad (regular ethernet user with a wi-fi device now lmao).

I notice that the no team selection menu stuff that I had in all servers wasn't really a ping problem, because in my server I don't get team selection menu too. :P 

Something else `set ip 82.1.X.X` got server crash, but no problem.

Thanks :)

**Comment by a1batross** [comment]
About broken menu:

1) Try to reinstall the APK at first.
2) Check that there is no "couldn't exec touch/*" lines in game console.
3) If they appears, check extras.pak file in
/data/data/in.celest.xash3d.cs16client/files.
4) If there is no this file, post a new bug with an ADB logcat.
You still can get this file from APK: unpack it, find extras.pak and place
it in "cstrike" folder.

As a temporary workaround you can enable Old style menus and disable
extended menus in Multiplayer->Customize->Adv options.
