### ISSUE TITLE
Unable to load the libxash.so

### ISSUE THREAD

**Issue by TacoDeBoss** [SDLash3D/xash3d#157]
After setting up a Debian Jessie 32-bit dev environment to compile the project, I installed all the dependencies and compiled the project. It worked flawlessly, but when I attempt to run the xash3d executable on either the Debian Jessie 32-bit install, or my main Debian Sid 64-bit, it says "unable to load the libxash.so".

I have libxash.so, libxashmenu.so, vgui.so, and libvgui_support.so placed in the folder with the executable, as well as the content from the Steam version of Half-Life. I've tried compiling with VGUI support on and off, it makes no difference.

I would appreciate some help to solve this issue.

**Comment by TacoDeBoss** [comment]
This also happens when compiling from the "Without CMake" section from the Wiki.

**Comment by mittorn** [comment]
Use xash3d.sh script or run with LD_LIBRARY_PATH set to directory containing libxash.so

**Comment by TacoDeBoss** [comment]
@mittorn Thank you! It worked! But unfortunately the game isn't feeling quite right. Every first shot I fire from a weapon doesn't animate or play sound, movement feels slower than usual, gravity feels lower than usual, etc.
I'll try some tweaks and if I can't fix it, I'll report it as a bug. Thank you for your help.

**Comment by mittorn** [comment]
cl_lw 0

**Comment by TacoDeBoss** [comment]
@mittorn Thank you, that fixed the firing issue. I think I fixed the slowness by limiting my framerate. I noticed the speed of the game would fluctuate randomly but limiting my framerate seems to have fixed that.
