### ISSUE TITLE
CMake prevents linking

### ISSUE THREAD

**Issue by mittorn** [SDLash3D/xash3d#16]
CMakeFiles/xash.dir/CMakeFiles/2.8.10.2/CompilerIdC/CMakeCCompilerId.c.o:(.data.rel.local+0x0): multiple definition of `info_compiler'
CMakeFiles/xash.dir/CMakeFiles/2.8.10.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:(.data.rel.local+0x0): first defined here
CMakeFiles/xash.dir/CMakeFiles/2.8.10.2/CompilerIdC/CMakeCCompilerId.c.o:(.data.rel.local+0x4): multiple definition of `info_platform'
CMakeFiles/xash.dir/CMakeFiles/2.8.10.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:(.data.rel.local+0x4): first defined here
CMakeFiles/xash.dir/CMakeFiles/2.8.10.2/CompilerIdC/CMakeCCompilerId.c.o:(.data.rel.local+0x8): multiple definition of `info_arch'
CMakeFiles/xash.dir/CMakeFiles/2.8.10.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:(.data.rel.local+0x8): first defined here
CMakeFiles/xash.dir/CMakeFiles/2.8.10.2/CompilerIdC/CMakeCCompilerId.c.o: In function `main':
CMakeCCompilerId.c:(.text+0x0): multiple definition of `main'
CMakeFiles/xash.dir/CMakeFiles/2.8.10.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:CMakeCXXCompilerId.cpp:(.text+0x0): first defined here
collect2: ошибка: выполнение ld завершилось с кодом возврата 1
make[2]: *** [engine/libxash.so] Ошибка 1
make[1]: *** [engine/CMakeFiles/xash.dir/all] Ошибка 2

**Comment by a1batross** [comment]
Похоже на какую-то ошибку внутри CMake. Это у тебя на ARM происходит?
