### ISSUE TITLE
Compile VGUI for other platform?

### ISSUE THREAD

**Issue by cia48621793** [SDLash3D/xash3d#18]
I'd like to compile Xash3D for Raspberry Pi(as the android phone could do well, why not with Pi that have a better CPU and GPU?) but the VGUI library supplied in linux/ folder is x86 only, I cannot find an option to compile VGUI, otherwise I have to go no-GUI.

**Comment by a1batross** [comment]
VGUI is proprietary library only for x86. There is no open source
alternative.

At android port branch VGUI is enabling by one click. By default, vgui is
disabled. If you try compile Xash3D with vgui on non-x86 architecture, you
will get compile error (look at common/port.h)

vgui-less client library you can find at XashXT repository. This client
have full GUI and works with HLSDK server. But only for Half-Life.

**Comment by cia48621793** [comment]
I'll try to port VGUI if I could have time, too sad it's proprietary of Valve.
