### ISSUE TITLE
Compiling for in Raspberry Pi/ARM?

### ISSUE THREAD

**Issue by cia48621793** [SDLash3D/xash3d#19]
I'd like to build Xash3D for Pi 2, somehow we'd need some special treatment to make it ok, I do have compiled Xash3D engine and UI part(also hl_cdll), but it still falls back to dedicated mode.

The Pi 2 features a four-core, 900MHz(Overclockable, my maximum settings is 1.1GHz), Cortex-A7, 1GB of LPDDR2 memory and a powerful VideoCore IV GPU capable of running OpenGL ES 2.0, and is comparable to the GPU of the first-generation Xbox.
I guess it's well enough for Pi 2 to drive Xash3D, at least 30 frames per seconds, but I'm quiet busy, I have 3 projects to do right now, so I cannot concentrate on Xash3D right now, if someone does have Xash3D running HL1 with graphics in Pi, please comment below to show how did you make it!

**Comment by a1batross** [comment]
@mittorn is working on ARM Linux version. 
Xash3D and HLSDK server have some issues with ARM because code originally wrote for x86 and never tested on ARM.

**Comment by cia48621793** [comment]
If I have free time, I'd join the frontline too, thought my main programming languages is C++ and C#.

**Comment by a1batross** [comment]
Just compile it with CMake.
