### ISSUE TITLE
redefinition of typedef ‘msurface_t'

### ISSUE THREAD

**Issue by sballu** [SDLash3D/xash3d#20]
Causes an error in osx ;)

common/com_model.h:208: error: redefinition of typedef ‘msurface_t’
common/com_model.h:135: error: previous declaration of ‘msurface_t’ was here

**Comment by a1batross** [comment]
Clang compiler?

**Comment by sballu** [comment]
gcc compiler

In last valve's com_model.h, you have : 
struct msurface_s { ... };
and not msurface_s { ... } msurface_t;

**Comment by a1batross** [comment]
Strange, it compiles on my Linux host. 
Xash3D, AFAIK, is using custom common headers. But I anyway will try to fix that. =)

**Comment by sballu** [comment]
It works in my Linux too, maybe it's the gcc version on my OSX.

**Comment by a1batross** [comment]
Try to fix another errors by yourself, I don't have Mac computer and can't test it. 

P.S. Compile only 32-bit version. On 64-bit there is some problems.

**Comment by sballu** [comment]
Thx mate.
