### ISSUE TITLE
Crash in pfnIsSpectateOnly () when connecting to server or restarting server

### ISSUE THREAD

**Issue by mittorn** [SDLash3D/xash3d#35]
at return pPlayer ? (pPlayer->curstate.spectator != 0) : 0;

**Comment by a1batross** [comment]
Seems doesn't crash if HLSDK client isn't used. 

And if game exits with Host_EndGame.

**Comment by mittorn** [comment]
Solved?

**Comment by mittorn** [comment]
Solved
