### ISSUE TITLE
vgui font rendering is broken

### ISSUE THREAD

**Issue by mittorn** [SDLash3D/xash3d#36]
Scoreboard fonts does not render on valve's client

**Comment by a1batross** [comment]
I think this is just fontconfig settings. On my PC scoreboard works.

**Comment by mittorn** [comment]
It is because of missing fonts in gfx folder. But in GS  it works without these fonts.

**Comment by a1batross** [comment]
I think GS just uses system fonts.

15:15, пт, 03.07.2015, mittorn <notifications@github.com>:

**Comment by mittorn** [comment]
Solved as it works after fixing gfx files.
