### ISSUE TITLE
Compiling with error

### ISSUE THREAD

**Issue by Nazar2805** [SDLash3D/xash3d#44]
Terminal: https://goo.gl/1MID3H
CMakeOutput.log: https://goo.gl/HH5CR2
Distro: OpenSUSE 13.2 KDE
SDL2-devel, SDL2_image-devel, pkg-config, cmake, SDL2_mixer-devel, SDL2_gfx-devel installed

**Comment by a1batross** [comment]
Fixed in 6e8add7.
