### ISSUE TITLE
PixelFormat and SDL

### ISSUE THREAD

**Issue by a1batross** [SDLash3D/xash3d#5]
Need to know what is the sense of VID_ChoosePFD() in engine/client/gl_vidnt.c.

**Comment by JoelTroch** [comment]
I'm not an OpenGL expert but I've found these, hope it can help you :

https://msdn.microsoft.com/en-us/library/windows/desktop/dd368826(v=vs.85).aspx
http://stackoverflow.com/questions/2540442/what-is-the-pixelformatdescriptor-parameter-in-setpixelformat-used-for

**Comment by a1batross** [comment]
Already seen it. 
Also found this https://msdn.microsoft.com/en-us/library/windows/desktop/dd368991(v=vs.85).aspx
