### ISSUE TITLE
Changing screen resolution  Problem !!!!!

### ISSUE THREAD

**Issue by msmx1000** [SDLash3D/xash3d#62]
Hi there ,recently i downloaded Xash3d and i build it using visual studio 2010 in debug mode,
but when i try to test my halflife Mod which i also build it in debug mode,the engine(Xash3D)
crashes(When trying to change screen resolution or starting new game ) while the Mod work perfectly with the original valve engine,and not only my mod crashes with Xash but all other mods too.
So i debugged the program and  client.dll file, and the result was that the game crashes at this file vgui_TeamFortress Viewport.cpp When trying to execute this line:
App::getInstance()->setScheme(pScheme) located in TeamFortressViewport::TeamFortressViewport() 
function
Please help!!!!

**Comment by mittorn** [comment]
You need to use vgui from steam version.
Other solution is to build vgui_support.dll with vgui.lib from old sdk.

**Comment by msmx1000** [comment]
Well,i copied both vgui.dll and steam.dll files from CS 1.8 game i have and tried to run cstrike Mod and it worked fine, so the problem of changing the screen resolution gone(thank you),but even though when i try to run any map the engine just not responding and it start eating my CPU

**Comment by msmx1000** [comment]
Well, I copied both vgui.dll and steam.dll files from CS 1.8 game i have,and the problem of changing screen resolution disappeared (Thanks to you), but even though when i try to run any map the computer just freeze and the game just don't respond,also even when i copied vgui.dll from steam game (CS 1.8) i still cant get rid of vgui_support.dll or the engine wont work or even start

**Comment by msmx1000** [comment]
Problem Solved thank you!!!!!!

**Comment by msmx1000** [comment]
Hi again, after solving the problem of vgui a new problem came to scene,
the problem is that when i try to run a map ,the engine and so computer freez with CPU usage up to 100% and the console output is:

**Comment by msmx1000** [comment]
Hi again, after solving the problem of vgui a new problem came to scene,
the problem is that when i try to run a map ,the engine and so computer freez with CPU usage up to 100% and the console output is: 
map boot_camp
Dll loaded for mod Half-Life
Server loaded
Spawn server:boot_camp
executing skill.cfg
Game Skill Level : 1
0 entities inhibited
Game started
