### ISSUE TITLE
Bilinear filtering is always performed on skybox textures, even when GL_TEXUREMODE cvar is GL_NEAREST.

### ISSUE THREAD

**Issue by ShaunNoWay** [SDLash3D/xash3d#63]
Tried to fix this myself by tinkering with the source code, but I just don't have the skill. Could we please get a patch for this?

Thanks.

**Comment by mittorn** [comment]
It seems that sky draw performed separately. It goes from quake.

**Comment by mittorn** [comment]
If just want to force GL_NEAREST on sky, just add TF_NEAREST flag to TF_SKY defination (gl_local.h)

**Comment by ShaunNoWay** [comment]
Hey, that worked! Shame we can't have it follow the cvar, but I never play with bilinear filtering on anyway. You're the best. Thanks so much!

**Comment by mittorn** [comment]
It may be implemented in cvar, it seems to be some problem in R_TexFilter
