### ISSUE TITLE
Loading Map Problem

### ISSUE THREAD

**Issue by msmx1000** [SDLash3D/xash3d#64]
Hi again, after solving the problem of vgui a new problem came to scene,
the problem is that when i try to run a map ,the engine and so computer freez with CPU usage up to 100% and the console output is:
map boot_camp
Dll loaded for mod Half-Life
Server loaded
Spawn server:boot_camp
executing skill.cfg
Game Skill Level : 1
0 entities inhibited
Game started 
----------------------------------------------------------------
I searched up the engine  source and found that function called: SV_LevelInit located in sv_init.c
file make use of some function called SV_EntityScript( ) which in turn look for a file with .ent extension (which i never ever heard about it before) to decide which entities to load from a given map.
How can i load a map or find this entity files?

**Comment by a1batross** [comment]
Can you run engine with -dev 5 parameter and post log here?

**Comment by msmx1000** [comment]
Well,After adding the -dev 6 ,the console print a lot of things which
i cant list it all here,but here is the list of Errors:

1- if i build the client.dll directly from halflife source i get 
a Message at startup telling that entry point GetMousePos@Surface@vgui
failed to initialize and then console print this:
Error:Sys_LoadLibrary : loading cl_dlls/client - failed 

2- if i used the client.dll library that already come with halflife game 
console print this:
Sys_LoadLibrary : loading cl_dlls/client - ok
CL_LoadProgs: found single callback export
CL_LoadProgs:failed to get address of HUD_GetRenderInterface proc
CL_LoadProgs:failed to get address of HUD_GetPlayerTeam proc
CL_LoadProgs:failed to get address of HUD_ClipMoveToEntity proc
CL_LoadProgs:failed to get address of IN_ClientTouchEvent proc
CL_LoadProgs:failed to get address of IN_ClientMoveEvent proc
CL_LoadProgs:failed to get address of IN_ClientLookEvent proc
.......
then after loading boot_camp map console print:
CL_PrepSound:boot_camp
CL_PrepVideo:boot_camp
...then it crashes...at line 
App::getInstance()->setScheme(pScheme);
in function TeamFortressViewport()
as the debugger shows,
and that's happens when i use vgui_support.dll
library, but if i used vgui steam library
the game crashes immediately 

3- if i used CS 1.8 Mod the console print this error :
Error:Sys_LoadLibrary : couldnt load encrypted library cl_dlls/client.dll
-----------------------------------------------------------------------------
In all three cases the map loads perfectly and all entities and models
spawned and no entities inhibited 
So the problem is always related to client.dll library and\or Vgui library
