### ISSUE TITLE
 Using Xash with WON vgui.dll [SOLVED]

### ISSUE THREAD

**Issue by msmx1000** [SDLash3D/xash3d#65]
Well,After adding the -dev 6 ,the console print a lot of things which
i cant list it all here,but here is the list of Errors:

1- if i build the client.dll directly from halflife source i get
a Message at startup telling that entry point GetMousePos@Surface@vgui
failed to initialize and then console print this:
Error:Sys_LoadLibrary : loading cl_dlls/client - failed

2- if i used the client.dll library that already come with halflife game
console print this:
Sys_LoadLibrary : loading cl_dlls/client - ok
CL_LoadProgs: found single callback export
CL_LoadProgs:failed to get address of HUD_GetRenderInterface proc
CL_LoadProgs:failed to get address of HUD_GetPlayerTeam proc
CL_LoadProgs:failed to get address of HUD_ClipMoveToEntity proc
CL_LoadProgs:failed to get address of IN_ClientTouchEvent proc
CL_LoadProgs:failed to get address of IN_ClientMoveEvent proc
CL_LoadProgs:failed to get address of IN_ClientLookEvent proc
.......
then after loading boot_camp map console print:
CL_PrepSound:boot_camp
CL_PrepVideo:boot_camp
...then it crashes...at line
App::getInstance()->setScheme(pScheme);
in function TeamFortressViewport()
as the debugger shows,
and that's happens when i use vgui_support.dll
library, but if i used vgui steam library
the game crashes immediately

3- if i used CS 1.8 Mod the console print this error :
Error:Sys_LoadLibrary : couldnt load encrypted library cl_dlls/client.dll

In all three cases the map loads perfectly and all entities and models
spawned and no entities inhibited
So the problem is always related to client.dll library and\or Vgui library

**Comment by msmx1000** [comment]
[SOLVED]
 i just used Original_Xash3d vgui include files and static library to build both SDLash3D project and client.dll library project and now the game work perfectly with both vgui.dll versions (steam and WON)
and the problem of GetMousePos entry point vanished.
and that's mean that there is a problem with the vgui headers and library shipped with half-life

**Comment by mittorn** [comment]
Does engine built with old headers work with new vgui and new clients?

**Comment by msmx1000** [comment]
well i think so,i did test it with several client.dll libraries and with both vgui versions.

**Comment by mittorn** [comment]
Can you give me vgui_support.dll for old vgui?
I think, it should be distributed with windows builds.
