### ISSUE TITLE
Limited mouse-look on Opposing Force

### ISSUE THREAD

**Issue by ShaunNoWay** [SDLash3D/xash3d#66]
Video:
https://youtu.be/DbZCi3K7ayc

My view along the horizontal axis is limited to about 90 degrees, and 45 degrees along the vertical axis. This only happens with the mouse; the *+left* and *+right* commands work fine.

The original Half-Life, as well as Blue Shift and every other Half-Life mod I've tried don't have this problem. It's only on Opposing Force

I'm using a fresh install of the Steam version of Opposing Force.

**Comment by a1batross** [comment]
Enable Mouse Look in controls settings. I have no idea, why it disabled by default.

**Comment by ShaunNoWay** [comment]
I made sure mouse look in the menu was enabled, and even typing *+mlook* in the console, but the problem still persists. Strangely enough, look-strafe is capped as well. Seems anything having to do with my mouse is busted for some reason.
https://youtu.be/V4g2aeENNrw

**Comment by a1batross** [comment]
Try set m_valvehack 1. 

It looks like an old bug in client.dll with SDL mouse.

**Comment by ShaunNoWay** [comment]
Nope, didn't work. I also tried *m_enginemouse* but that didn't do anything either.

**Comment by a1batross** [comment]
Very strange. I need to test this on my Windows machine.

**Comment by mittorn** [comment]
It seems to have problems with new client on windows. And it seems that m_valvehack does not work on windows. It must reset mouse position in sdl when it outs of some region of screen window.

**Comment by ShaunNoWay** [comment]
Ah, okay. Thanks for looking into it, guys. If it matters, I'm on Windows 10.

**Comment by mittorn** [comment]
Mouse is limited to window bounds.
Maybe, we need to force relative mouse mode in SDL?
Old client resets mouse position via WINAPI, new gets relative position via SDL.

**Comment by mittorn** [comment]
Look at that function:
https://github.com/SDLash3D/xash3d/blob/master/engine/common/input.c#L469
Try make mouse warp work with cvars.
GoldSource engine has hack for some clients, that enables relative mode, it is fltered by gamedir.

**Comment by ShaunNoWay** [comment]
I put this at the top of the function and I can look around freely now:
`if (true)`
`{`
`SDL_SetRelativeMouseMode(SDL_TRUE);`
`}`
But now I can't see my cursor on the menu screens anymore. I can still click on stuff, it's just my cursor is invisible.

**Comment by ShaunNoWay** [comment]
For now, I just made *SetRelativeMouseMode* follow a cvar which I can turn off whenever I need to use the pause menu. Hopefully we can get a more sophisticated fix.

Again, thanks so much. You guys are awesome.

**Comment by a1batross** [comment]
LOL. 

Engine automatically enables RelativeMouseMode when it is in-game. And disables is menu, console, AVI playing. Try to disable m_valvehack.

**Comment by ShaunNoWay** [comment]
Is that why I can't skip intro AVIs like I can on Uncle Mike's original? Anyway, I set *m_valvehack* cvar to *0* and nothing happened.

**Comment by a1batross** [comment]
I reopened it to not.forget reproduce this bug on my Windows 10.

Strange that mouse isn't centering automatically. 

Also, AVI skipping is really important.

**Comment by mittorn** [comment]
Please check mouse in last version

**Comment by ShaunNoWay** [comment]
Trying to compile the latest source code gives me this error:
`xash3d-master\vgui_support\vgui_main.h(26): fatal error C1083: Cannot open include file: 'VGUI.h': No such file or directory`

![vgui_main](https://cloud.githubusercontent.com/assets/14033754/13519621/455acc96-e1a7-11e5-9ffc-fb21b7a79b36.png)

**Comment by ShaunNoWay** [comment]
Got vgui_support to compile. I didn't know that you need to put the Half-Life SDK within the Xash3D project folder. Anyway, I am now able to run Opposing Force without any mouse problems. Thanks, Mittorn.

**Comment by mittorn** [comment]
You can use already working copy of vgui_support
It's API is stable now, so you do not need to change anything in it.
