### ISSUE TITLE
No sound or animations on weapons

### ISSUE THREAD

**Issue by ShaunNoWay** [SDLash3D/xash3d#68]
**Video:**
https://youtu.be/Ccsti2UcQYQ

I just built the latest version of the Xash3D engine and I'm getting this bug on Opposing Force. Tried reinstalling Opposing Force but it still happens. I'm also not getting this bug on the original Half-Life.

**Edit:** I am now getting this bug on the original Half-Life.

**Comment by a1batross** [comment]
Weapon.predicting is still incomplete. 
There is two ways:
1) Enable cl_predict.
2) Disable cl_lw.

**Comment by ShaunNoWay** [comment]
Disabling cl_lw did it.
Thanks again.
