### ISSUE TITLE
Sparkshower above stuck monsters

### ISSUE THREAD

**Issue by ShaunNoWay** [SDLash3D/xash3d#69]
When a monster tries to move and gets stuck on something, whether it be a brush or another entity, a sparkshower is rendered above them. Though this is perhaps useful to developers, I find it kinda distracting during normal gameplay, so I tried to disable it. Unfortunately, I can't find the code that makes this happen. Could someone point me in the right direction?
![stuck](https://cloud.githubusercontent.com/assets/14033754/10407743/380a6c98-6ebd-11e5-8f34-b52d579c14a0.jpg)
Thanks.

**Comment by a1batross** [comment]
Yeah, this is has been used when we debugged NPC movement on Android/ARM. 

You can disable it by recompiling hl.so(or hl.dll) from HLSDK without _DEBUG macro.

**Comment by ShaunNoWay** [comment]
Oh, oops. I thought this was from Xash, since I hadn't been experiencing it in vanilla Half-Life. Sorry.
