### ISSUE TITLE
A bunch of old bugs

### ISSUE THREAD

**Issue by Matthaiks** [SDLash3D/xash3d#76]
Confirmed in Xash3D build3153 with extras:
https://github.com/ValveSoftware/halflife/issues/383
https://github.com/ValveSoftware/halflife/issues/692
https://github.com/ValveSoftware/halflife/issues/693
https://github.com/ValveSoftware/halflife/issues/867

**Comment by a1batross** [comment]
We are using original half life game code. It's not bugs of engine.

**Comment by Matthaiks** [comment]
Oh OK.

**Comment by a1batross** [comment]
You can duplicate this in SDLash3D/halflife. Maybe it will be fixed. :)
