### ISSUE TITLE
Gluon Gun's "energy cloud" (impact animation) dissapears in multiplayer

### ISSUE THREAD

**Issue by Matthaiks** [SDLash3D/xash3d#77]
It's fine in singleplayer, though.

Xash3D build3153 with extras

**Comment by a1batross** [comment]
I investigated, that the sprite shows one frame in multiplayer(in case, if we have sprites/XSpark1.spr, instead sprites/xspark1.spr).

**Comment by a1batross** [comment]
Checked a GoldSource HL. It's an expected behaviour. So I will close it.
