### ISSUE TITLE
[EntTool] some keyvalues of entity are not updated after ent_create or ent_fire

### ISSUE THREAD

**Issue by steadyfield** [SDLash3D/xash3d#98]
I'm using the latest release.
The OS is Windows 8.1
https://github.com/SDLash3D/xash3d/releases/latest

I was using EntTools commands to create a func_tankrocket and a func_tankcontroller entities.

I have incorporated the commands in two scripts (.cfg file) and use 'exec' command to run it. The scripts work well in the Android version of Xash3D.

I succeeded in creating those entities, I can control the func_tankrocket turret to fire, but I can't control the turrent to rotate, which means that the yawrate, yawrange, pitchrate, pitchrange keyvalues are not actually updated after the ent_fire commands.

My scripts are working in the Android version and I can rotate the turret:
http://cs630322.vk.me/v630322982/25c4/avg29Dg-Xxs.jpg

But it's not working in the Windows version.

Here is the two .cfg file.

ct.cfg (create_tank)
sv_enttools_enable 1
wait
sv_enttools_maxfire 100
wait
sv_enttools_players 1
wait
//creating the main func_tank
ent_create func_tankrocket model models/w_rpg.mdl spawnflags 32 targetname ply_rocket1
wait
//the following command might not be properly executed
//setting the keyvalues of the tank
ent_fire ply_rocket1 set yawrate 120
wait
ent_fire ply_rocket1 set yawrange 360
wait
ent_fire ply_rocket1 set yawtolerance 15
wait
ent_fire ply_rocket1 set pitchrate 120
wait
ent_fire ply_rocket1 set pitchrange 360
wait
ent_fire ply_rocket1 set pitchtolerance 5
wait
ent_fire ply_rocket1 set barrel 45
wait
ent_fire ply_rocket1 set barrelz -6
wait
ent_fire ply_rocket1 set spritescale .5
wait
ent_fire ply_rocket1 set firerate 5
wait
ent_fire ply_rocket1 set bullet_damage 22
wait
ent_fire ply_rocket1 set persistence 1
wait
ent_fire ply_rocket1 set spriteflash sprites/muzzleflash2.spr
wait
ent_fire ply_rocket1 set firespread 1
wait
//move up 25 units
ent_fire ply_rocket1 moveup

ctc.cfg (create_tank_controller)
sv_enttools_enable 1
//creating the controller of the func_tank, press E on the tankcontroller entity to control the tank
ent_create func_tankcontrols target ply_rocket1 model models/w_weaponbox.mdl
ent_create func_wall model models/w_weaponbox.mdl

**Comment by a1batross** [comment]
Try to save/load game. Some parameters doesn't update until restart. For
example, model changing.
18.12.2015 17:31 пользователь "steadyfield" <notifications@github.com>
написал:

**Comment by steadyfield** [comment]
@a1batross I tried save/load. It still didn't work. cannot rotate the turret.

Also, I created a SAVE in the Android version. I sent it to the PC and load it in the PC version of Xash3d. In the game, the turret can be rotated left or right, but it can't be rotated up or down.

**Comment by mittorn** [comment]
I am expierensing same problem on linux. Try with different fps (fps_max).
Note that it may depend on server library version.
keyvalues are handled in server code.
And it made to initialize values on map, but not to upddate it in runtime, so some features may not work correctly at all.
I'll test your script later.

**Comment by steadyfield** [comment]
@mittorn maybe a custom version of server DLL can be built with HLSDK, just like the Android version.

**Comment by mittorn** [comment]
Android uses recent hlsdk, so behaviour should not differ.
It is very strange

**Comment by steadyfield** [comment]
@mittorn does this commit fix the issue?

https://github.com/SDLash3D/xash3d/commit/c0eba49344954c16b5c30a8c0b2d4f4db0d14a22

**Comment by mittorn** [comment]
I have not tested it

**Comment by mittorn** [comment]
https://github.com/SDLash3D/xash3d/commit/f82e71e70a8b401c8380882982966179039d7c10
fixed
